export const PERMISSIONS = [
  "customers.view",
  "customers.create",
  "customers.edit",
  "customers.archive",
  "customers.assign",
  "customers.export",
  "customers.merge",
  "leads.view",
  "leads.create",
  "leads.edit",
  "leads.convert",
  "leads.assign",
  "leads.merge",
  "opportunities.view",
  "opportunities.edit",
  "campaigns.view",
  "campaigns.manage",
  "crm.import",
  "crm.routing",
  "projects.view",
  "projects.create",
  "projects.edit",
  "projects.assign",
  "projects.archive",
  "projects.transition",
  "requirements.view",
  "requirements.create",
  "requirements.edit",
  "requirements.approve",
  "tasks.view",
  "tasks.create",
  "tasks.edit",
  "tasks.assign",
  "tasks.override",
  "changes.view",
  "changes.create",
  "changes.approve",
  "comments.create",
  "comments.internal",
  "comments.moderate",
  "documents.view",
  "documents.upload",
  "documents.share",
  "documents.archive",
  "finance.view",
  "employees.view",
  "employees.manage",
  "settings.manage",
  "reports.view",
  "approvals.decide",
  "time.view",
  "time.log",
  "time.approve",
  "time.lock",
  "audit.view",
  "portal.access",
  "exports.create",
  "meetings.manage",
  "decisions.manage",
  "srs.view",
  "srs.edit",
  "srs.requirements",
  "srs.clarify",
  "srs.approve_requirements",
  "srs.approve",
  "srs.versions",
  "srs.publish",
  "srs.download_draft",
  "srs.download_approved",
  "srs.templates",
  "srs.signatures",
  "srs.internal",
  "srs.verify",
  "srs.respond",
  "srs.sign",
  "srs.admin",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL = [...PERMISSIONS];

const DELIVERY: Permission[] = [
  "projects.view",
  "projects.edit",
  "projects.assign",
  "projects.transition",
  "requirements.view",
  "requirements.create",
  "requirements.edit",
  "tasks.view",
  "tasks.create",
  "tasks.edit",
  "tasks.assign",
  "comments.create",
  "comments.internal",
  "documents.view",
  "documents.upload",
  "time.view",
  "time.log",
  "meetings.manage",
  "srs.view",
  "srs.clarify",
  "srs.internal",
  "srs.download_approved",
];

const SRS_CLIENT_ONLY: Permission[] = ["portal.access", "srs.respond", "srs.sign"];

export const ROLE_TEMPLATES: Record<string, { name: string; description: string; permissions: Permission[] }> = {
  system_admin: {
    name: "System administrator",
    description: "Full access, including settings and employee administration.",
    permissions: ALL.filter((permission) => !SRS_CLIENT_ONLY.includes(permission)),
  },
  owner: {
    name: "Company owner",
    description: "Full operational access for the software company.",
    permissions: ALL.filter((permission) => !SRS_CLIENT_ONLY.includes(permission)),
  },
  manager: {
    name: "Manager",
    description: "Organization workload, delivery, customers, and approvals.",
    permissions: ALL.filter(
      (permission) => !["settings.manage", "employees.manage", "srs.admin", "srs.templates"].includes(permission) && !SRS_CLIENT_ONLY.includes(permission),
    ),
  },
  project_manager: {
    name: "Project manager",
    description: "Plans and delivers software projects.",
    permissions: [
      ...DELIVERY,
      "projects.create",
      "projects.archive",
      "requirements.approve",
      "tasks.override",
      "changes.view",
      "changes.create",
      "changes.approve",
      "comments.moderate",
      "documents.share",
      "documents.archive",
      "approvals.decide",
      "customers.view",
      "reports.view",
      "exports.create",
      "decisions.manage",
      "time.approve",
      "employees.view",
      "srs.edit",
      "srs.requirements",
      "srs.approve_requirements",
      "srs.approve",
      "srs.versions",
      "srs.publish",
      "srs.download_draft",
      "srs.signatures",
      "srs.verify",
    ],
  },
  account_manager: {
    name: "Account manager",
    description: "Owns customer relationships and the sales pipeline.",
    permissions: [
      "customers.view",
      "customers.create",
      "customers.edit",
      "customers.archive",
      "customers.assign",
      "customers.export",
      "customers.merge",
      "leads.view",
      "leads.create",
      "leads.edit",
      "leads.convert",
      "leads.assign",
      "leads.merge",
      "opportunities.view",
      "opportunities.edit",
      "campaigns.view",
      "campaigns.manage",
      "projects.view",
      "projects.create",
      "comments.create",
      "comments.internal",
      "documents.view",
      "documents.upload",
      "documents.share",
      "reports.view",
      "exports.create",
      "meetings.manage",
      "employees.view",
      "srs.view",
      "srs.edit",
      "srs.clarify",
      "srs.internal",
      "srs.download_draft",
      "srs.download_approved",
    ],
  },
  developer: {
    name: "Developer",
    description: "Delivers assigned project work and logs time.",
    permissions: DELIVERY,
  },
  designer: {
    name: "Designer",
    description: "Delivers design work on assigned projects.",
    permissions: DELIVERY,
  },
  qa: {
    name: "QA",
    description: "Verifies requirements and project work.",
    permissions: [...DELIVERY, "requirements.approve", "changes.view", "srs.verify", "srs.download_draft"],
  },
  finance: {
    name: "Finance",
    description: "Reviews commercial information, time, and exports.",
    permissions: [
      "finance.view",
      "time.view",
      "time.approve",
      "time.lock",
      "reports.view",
      "exports.create",
      "customers.view",
      "projects.view",
      "audit.view",
    ],
  },
  employee: {
    name: "Employee",
    description: "Baseline access for internal staff.",
    permissions: ["tasks.view", "tasks.edit", "comments.create", "comments.internal", "documents.view", "time.log", "time.view"],
  },
  customer: {
    name: "Customer",
    description: "Access limited to the customer's own organization.",
    permissions: [
      "portal.access",
      "projects.view",
      "requirements.view",
      "tasks.view",
      "changes.view",
      "changes.create",
      "comments.create",
      "documents.view",
      "approvals.decide",
      "srs.view",
      "srs.respond",
      "srs.clarify",
      "srs.sign",
      "srs.download_approved",
    ],
  },
};

export function hasPermission(permissions: readonly string[], permission: Permission) {
  return permissions.includes(permission);
}
